name: IaC-Validation
on: [push, pull_request]

jobs:
  checkov:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Checkov
        run: python -m pip install --upgrade pip && pip install checkov
      - name: Run Checkov
        run: checkov -d 03-iac-com-validacoes
