name: ci-cd-security
on:
  push:
  pull_request:

jobs:
  test:
    name: Unit tests (pytest)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 02-seguranca-containers
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: pip
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests
        run: pytest -q

  build_and_scan_image:
    name: Build Docker & Trivy (fail on CRITICAL)
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t devsecops-app ./02-seguranca-containers

      - name: Trivy image scan (CRITICAL -> fail)
        uses: aquasecurity/trivy-action@0.22.0
        with:
          scan-type: 'image'
          image-ref: 'devsecops-app:latest'
          severity: 'CRITICAL'
          format: 'sarif'
          output: 'trivy-results.sarif'
          exit-code: '1'

      - name: Upload Trivy SARIF
        if: ${{ always() }}
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: trivy-results.sarif

    dependency_check:
    name: OWASP Dependency-Check
    runs-on: ubuntu-latest
    needs: test
    permissions:
      contents: read
      security-events: write
      actions: read
    steps:
      - uses: actions/checkout@v4

      - name: Cache Dependency-Check database
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository/org/owasp/dependency-check-data
          key: dc-db-${{ runner.os }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            dc-db-${{ runner.os }}-

      - name: Run Dependency-Check (SARIF)
        uses: dependency-check/Dependency-Check_Action@v4
        with:
          project: "devsecops-app"
          path: "02-seguranca-containers"
          format: "SARIF"
          out: "reports"
          args: >
            --nvdApiKey ${{ secrets.NVD_API_KEY }}
            --failOnCVSS 0
        env:
          JAVA_OPTS: "-Xmx2g"

      - name: Upload Dependency-Check SARIF
        if: ${{ always() }}
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: reports/dependency-check-report.sarif

      - name: Upload reports artifact
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: dependency-check-reports
          path: reports/

